import logging
import re
import shutil
from pathlib import Path
import typing
import yaml

from sophios.api.pythonapi import Step, Workflow
import polus.tools.plugins as pp
from image.workflows.utils import OUT_PATH,MANIFEST_URLS


# Initialize the logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)



class CWLWorkflowBase:
    """
    Base class for CWL workflows to process imaging datasets.
    
    Attributes:
        work_dir: Path to working directory.
        name: Name of the dataset or workflow.
        container_engine: Choose container engine, either 'singularity' or 'docker'.
        out_dir: Directory for saving outputs.
    """
    def __init__(
        self,
        work_dir: Path, 
        name: str,
        inp_dir:Path,
        file_pattern:str,
        out_file_pattern:str,
        container_engine:typing.Optional[str]="singularity",
        out_dir: typing.Optional[Path] = OUT_PATH
    ):
        self.name = name
        self.inp_dir=inp_dir
        self.file_pattern = file_pattern
        self.out_file_pattern = out_file_pattern
        self.work_dir = work_dir
        self.container_engine = container_engine
        self.out_dir = out_dir
        self.adapters_path = self.work_dir.joinpath("cwl_adapters")
        self.wic_path = self.work_dir.joinpath("wic_workflows")
        for path in [self.adapters_path, self.wic_path]:
            if not path.exists():
                path.mkdir(parents=True, exist_ok=True)

    def _move_outputs(self) -> None:
        """Move output files and directories to the specified output directory."""
        logger.info("Moving directories and JSON files to output directory.")
        dir_names = {"autogenerated", "cachedir", "provenance", "outdir"}
        
        # Move specified directories
        for directory in self.work_dir.iterdir():
            if directory.name in dir_names:
                shutil.move(directory, self.out_dir)
        
        # Move JSON files
        for json_file in self.work_dir.rglob("*.json"):
            shutil.move(json_file, self.out_dir)

    @staticmethod
    def _to_camel_case(name: str) -> str:
        """Convert a plugin name to camel case."""
        return re.sub(r"(_|-)+", " ", name).title().replace(" ", "")

    @staticmethod
    def _extract_file_extension(pattern: str) -> str:
        """Extract and return the string after a period in the pattern."""
        match = re.search(r"\.(.*)", pattern)
        return f".*.{match.group(1)}" if match else ""

    @staticmethod
    def _escape_parentheses(pattern: str) -> str:
        """Escape parentheses and generate patterns for flatfield and darkfield correction."""
        pattern = re.sub(r"(\()|(\))", r"\\\1\2", pattern)
        return pattern.split("_c")[0] + "_c{c:d}" + re.sub(r"\d", "", pattern.split("_c")[1])

    def create_step(self, plugin_url: str) -> Step:
        """Create a step for the workflow based on the plugin manifest."""
        manifest = dict(pp.submit_plugin(plugin_url))
        plugin_version = str(manifest['version'])
        base_command = manifest['baseCommand']
        out_path = self.adapters_path.joinpath(f"{self._to_camel_case(manifest['name'])}.cwl")
        cwl_tool = pp.get_plugin(self._to_camel_case(manifest['name']), plugin_version).save_cwl(
            out_path)
        
        if self.container_engine == "singularity":
            self._modify_cwl(base_command, out_path.name)

        return Step(cwl_tool)
    
    @staticmethod
    def _get_manifest_url(plugin_name: str) -> str:
        """Retrieve the URL for the plugin manifest from GitHub."""
        return MANIFEST_URLS.get(plugin_name, "")

    def _modify_cwl(self, base_command:list[str], name:str) -> None:
        """Modify CWL files to include environmental variables and permissions."""

        for cwl_file in self.adapters_path.rglob(name):
            if "cwl" in cwl_file.name:
                try:
                    with cwl_file.open("r") as file:
                        config = yaml.safe_load(file)
                        config.setdefault("requirements", {})
                        config["requirements"]["ResourceRequirement"] = {"ramMin": 10240}
                        config["requirements"]["NetworkAccess"] = {"networkAccess": True}
                        
                    # Write the modified config back to the file
                    with cwl_file.open("w") as out_file:
                        yaml.dump(config, out_file, default_flow_style=False, sort_keys=False)
                        out_file.write(f"baseCommand: {base_command}\n")

                except FileNotFoundError:
                    logger.error(f"Error processing file: {cwl_file}")
    @staticmethod
    def image_pattern(pattern:str):
        """Modify out_file_pattern to get ome pattern."""

        # Split the filename at the period
        name_part, ext_part =  pattern.rsplit('.', 1) 
        # Add `.ome` before the `.tif` extension
        file_pattern = f"{name_part}.ome.{ext_part}"
        return file_pattern
